name: CI for HTML Project

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -errors -q index.html
