name: CI for HTML Project

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          echo "Checking HTML files..."
          find . -name "*.html" -exec tidy -e {} \;
