name: CI/CD with Jira and Slack

on:
  pull_request:
    types: [closed]

jobs:
  handle-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update Jira Issue Status When PR is Merged
        if: github.event.pull_request.merged == true
        run: |
          ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -o '[A-Z]\+-[0-9]\+')
          if [ -n "$ISSUE_KEY" ]; then
            echo "📌 Found Jira Issue Key: $ISSUE_KEY"
            RESPONSE=$(curl -s -o response.txt -w "%{http_code}" \
              -u ${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
              -X PUT \
              -H "Content-Type: application/json" \
              -d '{"fields":{"status":{"name":"DONE"}}}' \
              "${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/$ISSUE_KEY")

            if [ "$RESPONSE" = "204" ]; then
              echo "✅ Jira issue updated successfully."
            else
              echo "❗ Jira API returned status: $RESPONSE"
              cat response.txt
            fi
          else
            echo "❗ Không tìm thấy ISSUE_KEY trong tiêu đề PR. Bỏ qua cập nhật Jira."
          fi

      - name: Notify Slack when Jira issue is closed
        if: github.event.pull_request.merged == true
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"✅ Jira issue liên quan đến PR *#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}* đã được cập nhật sang trạng thái Done.\"
            }" \
            ${{ secrets.SLACK_WEBHOOK_URL }} || echo "⚠️ Slack notification failed"
