name: CI/CD with Jira and Slack

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  handle-events:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack when Issue is Closed
        if: github.event_name == 'issues' && github.event.action == 'closed'
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"🎉 Issue *#${{ github.event.issue.number }} - ${{ github.event.issue.title }}* has been closed!\"
            }" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Update Jira Issue Status When PR is Merged
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -o '[A-Z]\+-[0-9]\+')
          if [ -n "$ISSUE_KEY" ]; then
            curl -u ${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
              -X PUT \
              -H "Content-Type: application/json" \
              -d '{"fields":{"status":{"name":"Done"}}}' \
              "${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/$ISSUE_KEY"
          else
            echo "❗ Không tìm thấy ISSUE_KEY trong tiêu đề PR"
          fi
